### ISSUE TITLE
allowChange: false does not working.

### ISSUE THREAD

**Issue by blacksmoke26** [bainmullins/Raterater#1]
I tried to make readonly but option not working

$( '.ratebox' ).raterater( {
			starWidth: 14,
			//submitFunction: '',
			allowChange: false,
			spaceWidth: 1,
			numStars: 5
		});

Using latest build, is there anything wrong?

**Comment by RubenHarms** [comment]
This issue is solved in #2. Please close.

**Comment by RubenHarms** [comment]
@blacksmoke26
